name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Always fetch the branch that triggered the event (develop or master)
        ref: ${{ github.ref }}
    - name: Setup NodeJS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      # Simply use one single command for all that stuff and chain using &&
      run: yarn install --frozen-lockfile
    - name: Build package
      run: yarn build
    - name: Run unit tests
      run: yarn test
